from enum import IntEnum


class ErrorCode(IntEnum):
    AUTH_INVALID_CREDENTIALS = 10001
    AUTH_INVALID_PASSWORD = 10002
    AUTH_TOKEN_INVALID = 10004
    AUTH_ACCOUNT_LOCKED = 10005

    USER_NOT_FOUND = 20001
    USER_USERNAME_CONFLICT = 20002
    USER_INACTIVE = 20003
    USER_EMAIL_CONFLICT = 20004
    USER_PHONE_CONFLICT = 20005
    USER_CANNOT_DELETE_SELF = 20006

    ROLE_NOT_FOUND = 20007
    ROLE_NAME_CONFLICT = 20008
    ROLE_CANNOT_DELETE_SYSTEM = 20009
    ROLE_CANNOT_MODIFY_SYSTEM = 20010

    PERMISSION_NOT_FOUND = 20011

    PERM_INSUFFICIENT = 30001
    ROLE_INSUFFICIENT = 30002

    DATA_VALIDATION_FAILED = 40001

    BIZ_INSUFFICIENT_BALANCE = 50001
    BIZ_ORDER_EXPIRED = 50002

    DATASOURCE_NOT_FOUND = 60001
    DATASOURCE_NAME_CONFLICT = 60002
    SCRAPING_RULE_NOT_FOUND = 60003
    DATASOURCE_ALREADY_ACTIVE = 60004
    DATASOURCE_ALREADY_INACTIVE = 60005
    DATASOURCE_INACTIVE = 60006
    DATASOURCE_UNSUPPORTED_TYPE = 60007
    DATASOURCE_INVALID_CONFIG = 60008
    DATASOURCE_CONNECTION_FAILED = 60009
    DATASOURCE_UNKNOWN_TARGET_TYPE = 60010

    SYS_INTERNAL_ERROR = 90003


ERROR_CODE_TO_HTTP = {
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.AUTH_INVALID_PASSWORD: 401,
    ErrorCode.AUTH_TOKEN_INVALID: 401,
    ErrorCode.AUTH_ACCOUNT_LOCKED: 403,
    ErrorCode.USER_NOT_FOUND: 404,
    ErrorCode.USER_USERNAME_CONFLICT: 409,
    ErrorCode.USER_INACTIVE: 403,
    ErrorCode.USER_EMAIL_CONFLICT: 409,
    ErrorCode.USER_PHONE_CONFLICT: 409,
    ErrorCode.USER_CANNOT_DELETE_SELF: 400,
    ErrorCode.ROLE_NOT_FOUND: 404,
    ErrorCode.ROLE_NAME_CONFLICT: 409,
    ErrorCode.ROLE_CANNOT_DELETE_SYSTEM: 400,
    ErrorCode.ROLE_CANNOT_MODIFY_SYSTEM: 400,
    ErrorCode.PERMISSION_NOT_FOUND: 404,
    ErrorCode.PERM_INSUFFICIENT: 403,
    ErrorCode.ROLE_INSUFFICIENT: 403,
    ErrorCode.DATA_VALIDATION_FAILED: 422,
    ErrorCode.BIZ_INSUFFICIENT_BALANCE: 402,
    ErrorCode.BIZ_ORDER_EXPIRED: 410,
    ErrorCode.DATASOURCE_NOT_FOUND: 404,
    ErrorCode.DATASOURCE_NAME_CONFLICT: 409,
    ErrorCode.SCRAPING_RULE_NOT_FOUND: 404,
    ErrorCode.DATASOURCE_ALREADY_ACTIVE: 400,
    ErrorCode.DATASOURCE_ALREADY_INACTIVE: 400,
    ErrorCode.DATASOURCE_INACTIVE: 400,
    ErrorCode.DATASOURCE_UNSUPPORTED_TYPE: 400,
    ErrorCode.DATASOURCE_INVALID_CONFIG: 422,
    ErrorCode.DATASOURCE_CONNECTION_FAILED: 502,
    ErrorCode.DATASOURCE_UNKNOWN_TARGET_TYPE: 400,
    ErrorCode.SYS_INTERNAL_ERROR: 500,
}


def error_code_to_http_status(error_code: ErrorCode) -> int:
    return ERROR_CODE_TO_HTTP.get(error_code, 400)
