from __future__ import annotations

from pathlib import Path
from typing import Protocol

from pydantic import BaseModel, ConfigDict, Field

from src.core.agent.models import LocatorSpec


class DriverResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ok: bool = True
    data: dict[str, object] = Field(default_factory=dict)


class BrowserDriver(Protocol):
    def open(self, url: str | None = None, *, headed: bool = False) -> None: ...

    def close(self) -> None: ...

    def goto(self, url: str) -> DriverResult: ...

    def back(self) -> DriverResult: ...

    def reload(self) -> DriverResult: ...

    def click(self, locator: LocatorSpec) -> DriverResult: ...

    def fill(self, locator: LocatorSpec, value: str) -> DriverResult: ...

    def select(self, locator: LocatorSpec, value: str) -> DriverResult: ...

    def wait_visible(
        self,
        locator: LocatorSpec,
        timeout_seconds: float,
    ) -> DriverResult: ...

    def wait_network_idle(self, timeout_seconds: float) -> DriverResult: ...

    def scroll_down(self, amount: str | int | float | None = None) -> DriverResult: ...

    def scroll_up(self, amount: str | int | float | None = None) -> DriverResult: ...

    def scroll_to_element(self, locator: LocatorSpec) -> DriverResult: ...

    def extract_table(self, locator: LocatorSpec) -> DriverResult: ...

    def extract_list(self, locator: LocatorSpec) -> DriverResult: ...

    def extract_text(self, locator: LocatorSpec) -> DriverResult: ...

    def screenshot(self, filename: str) -> Path: ...

    def snapshot(self, filename: str, max_chars: int) -> str: ...

    def get_snapshot(self) -> str: ...

    def capture_screenshot(self) -> str: ...

    def state_save(self, path: Path) -> None: ...

    def state_load(self, path: Path) -> None: ...

    def current_url(self) -> str: ...

    def get_current_url(self) -> str: ...

    def title(self) -> str: ...

    def get_page_title(self) -> str: ...

    def text(self, locator: LocatorSpec) -> str: ...

    def get_element_text(self, locator: LocatorSpec) -> str: ...
