"""fix_user_stats_and_audit_fields

Revision ID: 06038dbc9807
Revises: 6a799160424b
Create Date: 2026-02-09 19:20:50.932208

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "06038dbc9807"
down_revision: Union[str, Sequence[str], None] = "6a799160424b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    # ### end Alembic commands ###
