"""add data_sources and scraping_rules tables

Revision ID: b25a49dc83a2
Revises: 000000000000
Create Date: 2026-02-04 11:59:45.275594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b25a49dc83a2"
down_revision: Union[str, Sequence[str], None] = "000000000000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "DOUYIN_SHOP",
                "DOUYIN_APP",
                "FILE_IMPORT",
                "SELF_HOSTED",
                name="datasourcetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ERROR", name="datasourcestatus"),
            nullable=False,
        ),
        sa.Column(
            "shop_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "account_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("cookies", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("proxy", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "api_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "api_secret", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("timeout", sa.Integer(), nullable=False),
        sa.Column("extra_config", sa.JSON(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_error_msg",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_sources_name"), "data_sources", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_data_sources_shop_id"), "data_sources", ["shop_id"], unique=False
    )
    op.create_table(
        "scraping_rules",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="scrapingrulestatus"),
            nullable=False,
        ),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "SHOP_OVERVIEW",
                "TRAFFIC",
                "PRODUCT",
                "LIVE",
                "CONTENT_VIDEO",
                "ORDER_FULFILLMENT",
                "AFTERSALE_REFUND",
                "CUSTOMER",
                "ADS",
                name="targettype",
            ),
            nullable=False,
        ),
        sa.Column(
            "granularity",
            sa.Enum("HOUR", "DAY", "WEEK", "MONTH", name="granularity"),
            nullable=False,
        ),
        sa.Column(
            "timezone", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("time_range", sa.JSON(), nullable=True),
        sa.Column("schedule", sa.JSON(), nullable=True),
        sa.Column(
            "incremental_mode",
            sa.Enum("BY_DATE", "BY_CURSOR", name="incrementalmode"),
            nullable=False,
        ),
        sa.Column("backfill_last_n_days", sa.Integer(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column("dimensions", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column(
            "dedupe_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("rate_limit", sa.JSON(), nullable=True),
        sa.Column(
            "data_latency",
            sa.Enum("REALTIME", "T_PLUS_1", "T_PLUS_2", "T_PLUS_3", name="datalatency"),
            nullable=False,
        ),
        sa.Column("top_n", sa.Integer(), nullable=True),
        sa.Column(
            "sort_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("include_long_tail", sa.Boolean(), nullable=False),
        sa.Column("session_level", sa.Boolean(), nullable=False),
        sa.Column("last_executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_execution_id",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_sources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scraping_rules_data_source_id"),
        "scraping_rules",
        ["data_source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scraping_rules_data_source_id"), table_name="scraping_rules")
    op.drop_table("scraping_rules")
    op.drop_index(op.f("ix_data_sources_shop_id"), table_name="data_sources")
    op.drop_index(op.f("ix_data_sources_name"), table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
